on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  container-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: jamacku/testing-farm-as-github-action@post
        with:
          api_key: ${{ secrets.TF_INTERNAL_API_KEY }}
          compose: "Fedora-latest"
          git_url: "https://github.com/sclorg/sclorg-testing-farm"
          git_ref: "master"
          tf_scope: "public"
          tmt_plan_regex: "fedora"
          update_pull_request_status: true
          pull_request_status_name: Test
          variables: "REPO_URL=${{ github.server_url }}/${{ github.repository }};REPO_NAME=${{ github.repository }};PR_NUMBER=${{ github.event.issue.number }};SINGLE_VERSION=${{ inputs.version }};OS=${{ steps.vars.outputs.os_test }};TEST_NAME=${{ steps.vars.outputs.test_name }}"
